---
ci:
    autofix_prs: false

fail_fast: false

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files
          - id: check-ast
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-toml
          - id: check-vcs-permalinks
          - id: check-xml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
          - id: name-tests-test
          - id: trailing-whitespace

  # Shell
    - repo: https://github.com/maxwinterstein/shfmt-py
      rev: v3.7.0.1
      hooks:
          - id: shfmt
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
            args: [-x]
  # Python
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 24.4.2
      hooks:
          - id: black
    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.12.0
      hooks:
          - id: reorder-python-imports
  # YAML
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
  # JSON
    - repo: https://gitlab.com/bmares/check-json5
      rev: v1.0.0
      hooks:
          - id: check-json5
  # C || C++ || Cuda
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v18.1.5
      hooks:
          - id: clang-format
            args: [--style=file]
            types_or: [c++, c, cuda]
            require_serial: true
    # - repo: https://github.com/cpplint/cpplint
    #   rev: 1.6.0
    #   hooks:
    #       - id: cpplint
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      hooks:
          # - id: cppcheck
          - id: clang-tidy
            args: [-checks=* -warnings-as-errors=*]
    # - repo: local
    #   hooks:
    #       - id: cppcheck-changed-lines
    #         name: cppcheck on changed lines
    #         entry: bash -c 'git diff --cached -U0 --no-color -- '*.c' '*.cpp' '*.h' '*.hpp' | filterdiff --addprefix=tmp/ | grep -v "^diff --git" | xargs
    #             cppcheck --addon=misra.py'
    #         language: system
    #         files: \.(c|cpp|h|hpp)$
    #         stages: [commit]

    #       - id: clang-tidy-changed-lines
    #         name: clang-tidy on changed lines
    #         entry: bash -c 'git diff --cached -U0 --no-color -- '*.c' '*.cpp' '*.h' '*.hpp' | filterdiff --addprefix=tmp/ | grep -v "^diff --git" | xargs
    #             clang-tidy'
    #         language: system
    #         files: \.(c|cpp|h|hpp)$
    #         stages: [commit]
    # Code linters and checks

    # # This won't run online...
    # - repo: local
    #   hooks:
    #       - id: ament_cppcheck
    #         name: ament_cppcheck
    #         description: Static code analysis of C/C++ files.
    #         stages: [commit]
    #         entry: env AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS=true ament_cppcheck
    #         language: system
    #         files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
    #       # - id: ament_cpplint
    #       #   name: ament_cpplint
    #       #   description: Static code analysis of C/C++ files.
    #       #   stages: [commit]
    #       #   entry: ament_cpplint
    #       #   language: system
    #       #   files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
    #       #   args: [--linelength=100, '--filter=-whitespace/newline,-build/include_order']
    #       - id: ament_lint_cmake
    #         name: ament_lint_cmake
    #         description: Check format of CMakeLists.txt files.
    #         stages: [commit]
    #         entry: ament_lint_cmake
    #         language: system
    #         files: CMakeLists\.txt$
    #       # - id: ament_copyright
    #       #   name: ament_copyright
    #       #   description: Check if copyright notice is available in all files.
    #       #   stages: [commit]
    #       #   entry: ament_copyright
    #       #   language: system
    #       # - id: clang-format
    #       #   name: clang-format
    #       #   description: Format files with ClangFormat.
    #       #   entry: clang-format-14
    #       #   language: system
    #       #   files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|js|m|proto|vert)$
    #       #   args: [-fallback-style=none, -i]
